### ISSUE TITLE
Multi-language support on error messages 

### ISSUE THREAD

**Issue by FelipeNBrito** [FelipeNBrito/FNBPasswordValidator#3]
Add support to return the error message by selected language (locale).  

## Summary

It would be nice to have support to multiple languages in the error messages.

As an international customer
I would like to be able to see the passoword erro feedback in my language
So that I can fix the password issues

## What needs to be done

- Create a structure to allow multiple languages 
- Translate to at least one new language

**Comment by SerhatKayaa** [comment]
so you just want to a language supporter like i18n right ? If it is please assign to me

**Comment by FelipeNBrito** [comment]
Yeah, that's the ideia 😀

**Comment by SerhatKayaa** [comment]
I created pr, can you look at that :)
